---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

language: zh-CN

title: 沈孙丰个人主页

favicon: https://www.baidu.com/favicon.ico

# 现代化主题配置
theme: dark
color: slate

# 背景配置 - 使用现代渐变背景
background:
  image: https://images.unsplash.com/photo-1557683316-973673baf926?auto=format&fit=crop&w=2560&q=80
  blur: md
  saturate: 80
  brightness: 40
  opacity: 85

# 卡片样式配置
cardBlur: sm
iconStyle: flat

# 布局配置
layout:
  常用网站:
    style: row
    columns: 4
    icon: mdi-web
  AI工具:
    style: row
    columns: 5
    icon: mdi-robot
  开发工具:
    style: row
    columns: 4
    icon: mdi-code-tags
  云服务:
    style: row
    columns: 4
    icon: mdi-cloud
  在线学习:
    style: row
    columns: 4
    icon: mdi-school
  设计资源:
    style: row
    columns: 4
    icon: mdi-palette
  娱乐休闲:
    style: row
    columns: 4
    icon: mdi-gamepad-variant
  影视制作:
    style: row
    columns: 5
    icon: mdi-movie-edit
  系统工具:
    style: row
    columns: 3
    icon: mdi-tools